apiVersion: v1
kind: Service

metadata:
  name: svc-pod-1

spec:
  type: NodePort
  selector:
    app: primeiro-pod
  ports:
    - port: 80
      #targetPort: 80  -- Porta a ser usada pelo nosso serviço
      nodePort: 30052 #Porta a ser usada externo Range 30000-32767
